### ISSUE TITLE
Is it possible to use api-routes in Production?

### ISSUE THREAD

**Issue by dillonco** [saltyshiomix/nextron#119]
I see in the api-routes example that it says it's not possible to use in Production but I was wondering if there's any change or how would you recommend running nodejs code and talking to the nextjs frontend?

**Comment by saltyshiomix** [comment]
Hi, @dillonco !
Thank you for your issue.

Nextjs' api-routes is based on an express server.
We should not start the server in the electron's main process because of the security issue.

We can use nodejs code only in the electron's main process(this is a secure server), and we can handle it with IPC communication :)

See the example [ipc-communication](https://github.com/saltyshiomix/nextron/tree/master/examples/ipc-communication).

**Comment by dillonco** [comment]
Ah thank you for explaining that, it makes sense now!

**Comment by lkleuver** [comment]
would be awesome to have IPC communication routes :)
