### ISSUE TITLE
Where can i put sqlite.db files ?

### ISSUE THREAD

**Issue by MuttakinHasib** [saltyshiomix/nextron#175]
hey, i want to fetch data from **SQLite** Database with `Knex, sqlite3`  ...

so where should i put my DB files ?

**Comment by lukeshumard** [comment]
I don't know the exact issue you are having, but I'm going to assume you want to have a local sqlite3 database that you can query from your main process. I had this same problem and here's what I did to accomplish this task.

### The Problem
When you package your Electron app, its contents are put into an archive format called [asar](https://github.com/electron/asar). You need your `.sqlite` file to be outside of the `app.asar` that gets created in order to use it with your database client.

### Solution
You can use the `extraResources` option in your `electron-builder` config to place the database file alongside the other resources and not within the `app.asar` file.

In this example, I have a folder in the root of my project called `databases` and it has a file called `test.sqlite`. Here is an example of what your `package.json` might look like.
```package.json
{
  "extraResources": ["databases/test.sqlite"]
}
```

You can verify that this worked by going to your packaged app and showing the resources. On Mac, this means right clicking the packaged app, clicking "Show Package Contents", and then navigating to Resources. You should see your `databases` folder and `test.sqlite` file.

### Path for the database
To get the path of your database in code, you can use a function like the following. Note: If your app is packaged, `app.getAppPath()` will return the `app.asar`. Since we are looking for a file outside of the archive, we need to set our base accordingly. This works both locally and packaged.
```ts
import { app } from 'electron'
import path from 'node:path'

const getDBPath = (filename): string => {
  let base = app.getAppPath()
  if (app.isPackaged) {
    base = base.replace('/app.asar', '')
  }
  return path.resolve(base, `databases/${filename}.sqlite`)
}

// example usage for 'test.sqlite' file
getDBPath('test.sqlite')
```

You can now trigger an IPC event on the renderer process that will get handled by your main process, query your database, and return the results back to the renderer process.

Here are some of the issues and documentation I looked at for help on this.
* [nextron#107 ](https://github.com/saltyshiomix/nextron/issues/107)
* [nextron#120 ](https://github.com/saltyshiomix/nextron/issues/120)
* https://github.com/electron-userland/electron-builder/issues/1474
* https://www.electron.build/configuration/contents#extraresources

**Comment by AlexisPiquet** [comment]
Maybe it can help you too.

On my side, I use mongoDB ([using atlas](https://docs.atlas.mongodb.com/tutorial/create-new-cluster/)) when [the app is online](https://www.electronjs.org/docs/latest/tutorial/online-offline-events).

And I use [NeDb](https://github.com/louischatriot/nedb) (a no longer maintained library) to store data locally where app is offline. 

When the application has an internet connection the user can sync both databases. (Using the ipcRenderer.invoke method). You can also developped a script to do it automatically in the main process.

Why NeDb, cause I like this project and is easly to syncronize with a mongodb database. (I mean, schema structure)

In my case I've added a folder named database in the root directory and I use [the path library from nodejs](https://nodejs.org/api/path.html) to resolve it.

**Comment by m5x5** [comment]
I'm marking this issue as resolved as we do not have enough information and there are two possible solutions in this issue.

**Comment by dxsuporte** [comment]
I used it that way, and everything worked out fine.

`const Path = require('path')

const config = {
  client: 'better-sqlite3',
  connection: {
    filename: Path.join(__dirname, __dirname.includes('app.asar') ? '../../database' : '/database'),
  },
  useNullAsDefault: true,
  migrations: {
    tableName: 'migrations',
    directory: Path.join(__dirname, '/migrations'),
  },
  seeds: {
    directory: Path.join(__dirname, '/seeds'),
  },
}
module.exports = require('knex')(config)`

**Comment by dxsuporte** [comment]
I used it that way, and everything worked out fine.

//##########################################

const Path = require('path')

const config = {
  client: 'better-sqlite3',
  connection: {
    filename: Path.join(__dirname, __dirname.includes('app.asar') ? '../../database' : '/database'),
  },
  useNullAsDefault: true,
  migrations: {
    tableName: 'migrations',
    directory: Path.join(__dirname, '/migrations'),
  },
  seeds: {
    directory: Path.join(__dirname, '/seeds'),
  },
}
module.exports = require('knex')(config)
