### ISSUE TITLE
Build fails for antd-typescript

### ISSUE THREAD

**Issue by maddygoround** [saltyshiomix/nextron#194]
Hi,

We are trying to build the app and resulting in the following error

```
- Generating static pages (0/4)
Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot assign to read only property 'children' of object '#<Object>'
```

Not sure what could be the cause.

**Comment by maddygoround** [comment]
It's an issue with _document.tsx file, once I removed it I am able to run the app.

After building the app I am not able to see anything on the screen. It just show the blank screen.

**Comment by saltyshiomix** [comment]
@maddygoround 

Thank you for reporting the issue!

Could you try nextron v7 or [this example](https://github.com/saltyshiomix/nextron/tree/d0f13abfb688e22000aa43ec014f407a2fbe39a7/examples/with-typescript-ant-design) ?

**Comment by saltyshiomix** [comment]
@maddygoround 

I can't reproduce this problem, so I close this issue for now.

If any updates, feel free to reopen the issue :)

**Comment by cellis** [comment]
I was able to reproduce, and ultimately solve this issue. The problem was I had `NODE_ENV=development` set in my `.zshrc` file. Nextron does set `NODE_ENV=production`, in the webpack build but electron build will take system NODE_ENV. So I needed to build with `NODE_ENV=production nextron build`. HTH someone searching.
