### ISSUE TITLE
question: how to setup tailwindcss jit mode?

### ISSUE THREAD

**Issue by VeoScript** [saltyshiomix/nextron#208]

**Comment by Rohithgilla12** [comment]
>To enable just-in-time mode, set the mode option to 'jit' in your tailwind.config.js 

Did you try this? @VeoScript

**Comment by VeoScript** [comment]
I tried it but it still doesn't work like custom font-size (**text-xs** to **text-[10px]**) , I also installed the latest tailwindcss.

**Comment by Venipa** [comment]
> I tried it but it still doesn't work like custom font-size (**text-xs** to **text-[10px]**) , I also installed the latest tailwindcss.

did you solve it? im unable to get any css from tailwind with jit but it does work with aot mode

**Comment by VeoScript** [comment]
it doesn't work, but im using aot mode instead

**Comment by spotnick** [comment]
I have a similar issue here. I found this video from simon from tailwind https://play.tailwindcss.com/cwqORB8ee7 and wanted to try it in my nextron app. 

Well it simply doesnt work. 

OC I adjusted it for react using className instead of class. Here is the code:

`<div className="relative">
                    <input
                        id="email"
                        name="email"
                        type="text"
                        className="peer h-10 w-full border-b-2 border-gray-300 text-gray-900 placeholder-transparent focus:outline-none focus:border-rose-600"
                        placeholder="john@doe.com"
                    />
                    <label
                        htmlFor="email"
                        className="absolute left-0 -top-3.5 text-gray-600 text-sm transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-2 peer-focus:-top-3.5 peer-focus:text-gray-600 peer-focus:text-sm">
                        Email address
                    </label>
                </div>`

and I also took care of the tailwind.config.js 

`const colors = require('tailwindcss/colors');

module.exports = {
    mode: 'jit',
    darkMode: false, // or 'media' or 'class'
    purge: ['./pages/**/*.{js,jsx,,tsx}', './src/**/*.{js,jsx,,tsx}'],
    theme: {
        colors: {
            rose: colors.rose,
        },
    },
    variants: {
        extend: {},
    },
    plugins: [],
};
`

Do we have a solution for this? I also found out that some hover: pseudo selectors are working, some are not, focus: is also not working. 

Has anybody an idea how to fix it? In a normal CRA its working :(
