### ISSUE TITLE
Questions regarding python integration

### ISSUE THREAD

**Issue by markolofsen** [saltyshiomix/nextron#21]
How to:
— integrate with python-shell (for using Python scripts with sqlite)
— build for windows?

**Comment by saltyshiomix** [comment]
@markolofsen 

Sorry for my late replying to your questions 😢 

I think it's possible to integrate with python-shell 👍 

But we should care about paths to the python scripts both of development mode and production build:

- if development mode, we can handle python scripts as usually.
- if production builds, we must copy python scripts to the `app` folder so that an `electron-builder` can handle them.

I'll try to add an example `with-python` this weekend :)

**Comment by markolofsen** [comment]
@saltyshiomix It would be cool, because I did not understand where to put the script.
Thanks

**Comment by saltyshiomix** [comment]
@markolofsen 

Added a python example, but it doesn't work on production builds.

@yoDon

Any ideas?

**Comment by saltyshiomix** [comment]
@markolofsen 

```bash
# install latest nextron
$ npm install --global nextron@latest

# use python example
$ nextron init test-app --template with-python
$ cd test-app
$ yarn && yarn dev
```

**Comment by yoDon** [comment]
Can you give more details than just "it doesn't work on production builds"?
What operating system are you using? 
Is there an error message you're seeing?

I didn't have a chance to build and run but looking at the with-python example code, my guess is the process spawning and killing code in background.js may be too simple. If the python executable is getting packed into the app.asar file then you need different syntax to execFile the packed file in production builds than you use to conventionally spawn an unpacked file in dev builds. I think you may also find more that in more realistic cases where the python process is a long-running process that the with-python example will leave python processes running because it doesn't properly clean up the launched python app when the app closes. Killing spawned processes in node is surprisingly tricky and what little guidance I could find on doing it right online didn't actually work reliably cross platform, which is one of the reasons I used the more complex approach of explicitly sending a shutdown message to the process in the with-python-typescript example. 

I understand you're trying to simplify the code in the with-python-typescript example by removing the web server/API and streamlining the spawn/kill logic, but I think the complexity that's there is manageable and is actually needed for non-trivial use cases. Whichever way you decide to go, it's probably best to use the same control path and logic for the -javascript and -typescript versions of the wih-python example.

I'm also not convinced I think baking the pyInstaller invocation into Nextron-build.js instead of keeping it in package.json is a good choice. You're intimately familiar with with contents of all the Nextron pipeline files so it's easy for you to put it there, but looking at it as someone who is just trying to npm install Nextron and start using it, the more critical steps (like how the python executable is built) you hide in places that new visitors don't know how to find, the more opaque the system feels. Building electron is a core part of Nextron and you've done a lot of work to make that easy so I get including that in the Nextron js but baking non-electron build processes into the custom Nextron code rather than listing them in package.json scripts feels counter to the way node packages are typically built and extended and like it's an approach that doesn't scale well to wanting dot net core and elixir and rust and etc as backends. I'll encourage you to at least consider the package.json scripts based approach I used in the with-python-typescript example (and I'll buy into whatever you decide, but I think it's at least worth considering).

Also, with regards to the with-python-typescript example, I made the change you requested in the PR for changing how the spawn is handled, but I confess I was puzzled by the need for it as I mainly run on Windows and the original code had been working fine during all my development (as I understand it the change you requested was to support Windows, which I think it already did).

**Comment by saltyshiomix** [comment]
Sorry, we remove the python examples because of few maintainers for now.

(Any PRs such as adding examples are welcome 👍 )

**Comment by bryantz13** [comment]
Hello, I have a question to ask you saltyshiomix. I have created a python file in renderer -> pages -> script-python -> python.py and I have used IPC to run the python file using the child_process spawn. In running the python file via IPC, I encountered a problem that When I start the system through localhost, the system can work normally, but when I build an App, the system cannot run the python file. What is the cause? And can you help me? Or is there any example? please help me

**Comment by bryantz13** [comment]
@saltyshiomix

**Comment by bm777** [comment]
@bryantz13, I assume everything works in dev mode. But when you go into prod mode, it doesn't.

In the current app, I'm developing, I succeeded in integrating other files in languages like Python and Rust.

A fact, in dev mode, it works because you control everything and it is easy to monitor in dev via debug. When it comes to go in prod, you should adopt another way to control the process in the main/background.js by using a shell script that you currently use to run your Python in dev.
Another, you should make sure that when you build the DMG file, you should notify the builder that it should import some additional resource like .sh, .rs, or .py file in `package.json` file like in the following:
```js
// **** other other fields: scripts, main, author, etc
 "build": {
    "extraFiles": [
      {
        "from": "python_folder/",
        "to": "python_folder/",
        "filter": "**/*"
      }
    ],
   // **** the rest: dependencies
  },
```

 - `"from": "python_folder"` could in the root folder of your project
 - `"to": "python_folder"` this will be placed exactly in your application in prod: in Mac, once you go to Applications/<yourAppName>/, right-click to go to open package Contents/, you should see your folder, if you see, now the next step is to run it via your main/background.js child_process.

In your main/background.js file, in prod, you can  navigate via the absolute path of __dirname which is exactly in `YouMacintosh HD/Applications/YourAppName/Contents/Resources/app.asar`. So you need to get path the absolute path or you script via 1 line:

```js
const parentDir = path.dirname(path.dirname(path.dirname(__dirname)))
const scriptPath = path.join(parentDir, 'python_folder/run.sh'); // run.sh is the file that run your Python file or Rust, or whatever :)
```

And you know now, how to run your child-process.
As I said, even in prod, you should have some control using logging that Sh give to us.
When you run the sh or the python, do something like this `sh ${scriptPath}  >> ~/.logging.log`.

----
As I said, the app I'm building an app, I have an hybrid backend Python + Rust. The end user don't have Python or Rust installed, so the key is to have Rust app and Python app executable.

 - Rust exec, is easy to compile and have a release via cargo.
 - Python exec, you can decide to use PyInstaller, but I'm more a fan of PyOxidizer (it is fast and light) but it is embedding Python interpreter in Rust.

**Comment by bm777** [comment]
@saltyshiomix I will PR a Python example next week.
