### ISSUE TITLE
Dependancy problem with material-ui 4.x and react 18

### ISSUE THREAD

**Issue by gabooh** [saltyshiomix/nextron#283]
If you create a new project like this : 

`npx create-nextron-app testapp --example with-javascript-material-ui`

You get an error like this when doing `npm install` :

```
user@computer:~/tmp/poub/testapp$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-nextron-app@1.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   dev react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.12.4
npm ERR! node_modules/@material-ui/core
npm ERR!   dev @material-ui/core@"^4.12.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by Nathan-html** [comment]
Hello, I have the same issue :/

**Comment by briosheje** [comment]
This happens because material-ui/core is the mui.com v4 version, which is meant to be used with either react 16 or 17.

For react 18, the correct package is `mui` which should be installed with: `npm install @mui/material @emotion/react @emotion/styled`.

The template should be updated, as the types and components imported should.

**Comment by saltyshiomix** [comment]
See also: https://github.com/saltyshiomix/nextron/pull/284
