### ISSUE TITLE
Simplest way to upgrade existing nextron?

### ISSUE THREAD

**Issue by armenr** [saltyshiomix/nextron#30]
Hey there! Thank you for all of your incredible and wonderful work.

My team loves me for having implemented Nextron into our repo. In turn, I remind and tell them about the fact that it's the maintainers of Nextron they should be loving :)

We do have a question, however:

What is the most straightforward way to update/upgrade our nextron implementation? :) 

Thank you!

**Comment by armenr** [comment]
@saltyshiomix - any potential advice? :)

**Comment by saltyshiomix** [comment]
Hi, @armenr !

Thank you for your testing nextron and your question!

Sorry I have no any ideas for now, because nextron is an app generator.
But I think it's so wonderful if it can check for updates and show diffs to patch like Git.

Anyway, I'll investigate the implementation this month 👍

**Comment by hadeeb** [comment]
How about making `nextron` a module like [`create-react-app`](https://facebook.github.io/create-react-app/), [`electron-webpack`](https://webpack.electron.build/) or [`preact-cli`](https://github.com/preactjs/preact-cli) ?
It will make upgrades easier.

`create-nextron-app` and `nextron` can be like `create-react-app` and `react-scripts`.

The helpers functions can be bundled into `nextron/helpers` or something, like `next/link`.

**Comment by hadeeb** [comment]
First of all, thanks for the well structured code. It was really easy going through it.

I have a working draft [here](https://github.com/hadeeb/nextron/tree/cli-poc).
Please have a look at it.

- No more path rewriting.
- Can use `next/link` and `<a>` tags.
- No more full page reloads on page transition (SPA like behaviour).
- Made `dev` and `build` commands part of `nextron` package, so that they can be updated independently.
- Moved `next`,`react` & `react-dom` to devDependencies -> `dmg` size reduced by ~9MB.

TODO
- Option to extend/modify webpack config.
- Port remaining examples.

If this is something you want to pursue, I am more than happy to help.

**Comment by saltyshiomix** [comment]
@hadeeb 

Thank you for your lots of advices in advance :)

<https://github.com/saltyshiomix/nextron/issues/30#issuecomment-499854160>

Here is [create-nextron-app](https://github.com/saltyshiomix/create-nextron-app) already.


<https://github.com/saltyshiomix/nextron/issues/30#issuecomment-500030425>

If you have some time, could you create a PR?
WIP-PR is also welcome :)

I'm so sorry for replying late and not working forward in this issue.

**Comment by saltyshiomix** [comment]
@armenr / @hadeeb 

Nextron v5 is out! (with Next.js v9)

```bash
$ npm install -g nextron@latest
```

Any advices are welcome 👍

**Comment by Psycokwet** [comment]
I'm closing this issue since it's been inactive for so long, as well as cleared since then. Have a good day !
