### ISSUE TITLE
Can't import 'electron' module or use ipcRenderer in nextjs pages folder. I keep getting error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by Abdul-Asa** [saltyshiomix/nextron#415]
Hi, I'm trying to create a nextron app with ipc communications but I keep getting an error anytime I import anything from the electron module. I've read similar issues on the github repo and even used the ipc example template but that doesn't work and no explicit fix on the issue. I figured this fix will be on the road map but it wasn't stated there either. How can I solve this? Any advice would be helpful. Thanks. 
<img width="986" alt="Screenshot 2023-10-11 at 15 41 54" src="https://github.com/saltyshiomix/nextron/assets/78966543/4a423cb8-b9f8-4d88-b0cc-1169ee042f3e">
<img width="994" alt="Screenshot 2023-10-11 at 15 43 25" src="https://github.com/saltyshiomix/nextron/assets/78966543/c8c04190-005c-47bb-b8aa-94bd600f7163">

**Comment by Mrx-dev** [comment]
same problem here

**Comment by makeusabrew** [comment]
This is the same issue as #413.

Unfortunately, the base template has recently been updated to follow long since established best practices of not allowing the renderer to access "privileged" modules (`electron` being one of them), but the examples haven't all caught up.

The very short term and **not recommended** fix is to swap the values of `nodeIntegration` and `contextIsolation` in `./main/helpers/create-window.ts`. That is, you want them to look like this:

```
const win = new BrowserWindow({
    ...state,
    ...options,
    webPreferences: {
      ...options.webPreferences,
      nodeIntegration: true,
      contextIsolation: false,
    },
  })
  ```
  
However, you shouldn't do this. As I recommended in #413, have a read of the official Electron IPC documentation, and follow those practices instead. It's not a great deal of work: you just need to expose a limited API to the renderer process via a preload script: https://www.electronjs.org/docs/latest/tutorial/ipc

Hopefully the examples will be updated in time (I would update the IPC one myself if I could find the time!)

**Comment by saltyshiomix** [comment]
I'll fix the bug soon, sorry for inconvenience 🙇

**Comment by saltyshiomix** [comment]
@Abdul-Asa CC: @Mrx-dev @makeusabrew 

Nextron v8.12.0 is out!
Now it supports preload script for secure IPC features :)

If you have time, please try new examples:

```
npx create-nextron-app test-app --example basic-lang-typescript
```

**Comment by Abdul-Asa** [comment]
It's all good and working now
Thank you @saltyshiomix and thanks for the advice @makeusabrew

**Comment by KaldrArt** [comment]
> @Abdul-Asa CC: @Mrx-dev @makeusabrew
> 
> Nextron v8.12.0 is out! Now it supports preload script for secure IPC features :)
> 
> If you have time, please try new examples:
> 
> ```
> npx create-nextron-app test-app --example basic-lang-typescript
> ```

great,  just use `window.ipc.send()` ~ thank you!

**Comment by Nithur-M** [comment]
I am still facing this issue on v9.4.0
Any workaround for this?
