### ISSUE TITLE
work with api route?

### ISSUE THREAD

**Issue by coderafei** [saltyshiomix/nextron#43]
next.js 9 provide [api route](https://nextjs.org/docs#api-routes)
nextron support it?

**Comment by saltyshiomix** [comment]
Sorry I don't know for now.
I'll investigate it later :)

**Comment by saltyshiomix** [comment]
@coderafei 

Added an [api-routes](https://github.com/saltyshiomix/nextron/tree/master/examples/api-routes) example as of `nextron@5.8.0` but it works **only** development mode.

We can't use API routes if the api url is localhost (the development server itself) when production build.

It is possible to use **only external** API urls with Electron. (because of security reasons)

**Comment by mdlindsey** [comment]
@saltyshiomix I see this issue is closed but is there any chance of revisiting this? The sole reason I tried Nextron was the hope of a server-side runtime in the production build; server-side runtime was the original purpose of NextJS.

**Comment by IbraheemHaseeb7** [comment]
nextron still today does not support api routes. Is there any quick alternative because I just completed my software and now I have come to this issue.

**Comment by Mogeiman** [comment]
any fixes yet?

**Comment by praveen-palanisamy** [comment]
One way to solve this issue is to use `electron-builder` directly. Here's a minimal example of the changes needed in your App's `package.json`:

```json
...
"scripts": {
    "dev": "npm run build && electron .",
    "build-renderer": "next build renderer",
    "build": "npm run build-renderer",
    "dist": "npm run build && electron-builder",
  },

 "devDependencies": {
    ...
    "electron": "^13",
    "electron-builder": "^23.0.3",
  },
 "build": {
    "asar": true,
    "files": [
      "main",
      "renderer/out"
    ]
  }
...
```
With the above, for a production build, you would run: `npm run dist`.
You can refer to this minimal [next.js example](https://github.com/vercel/next.js/tree/canary/examples/with-electron) or a more comprehensive [App that uses Next.js API routes with Electron.js](https://github.com/praveen-palanisamy/MemReFinder) for reference to upgrade your existing App.
[This answer on StackOverflow](https://stackoverflow.com/a/76398754/1310924) has more details if you are interested.

**Comment by nec-gv** [comment]
@praveen-palanisamy I'm having the same issue (created a simple Nextron app using `npx create-nextron-app`). I tried changing the `package.json` and `next.config.js` as you suggested and finally running `npm run dist`, however I can't make it work. Did anyone succeed using this method?

**Comment by megaacheyounes** [comment]
Just spent a whole week crafting a beautiful Nextron app to find out it will never work in production 
<img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbjgzYzZkbmU0N21tbTg4NTN0ampkc3pkMmowY20zZ2xkamljMG9icyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/jSxK33dwEMbkY/giphy.gif"/>

Seriously, Is API route support coming any time soon?

**Comment by IbraheemHaseeb7** [comment]
just use express js, i am already hating next js api routes

**Comment by im-ramon** [comment]
@megaacheyounes , the SAME problem!

**Comment by ikangjie** [comment]
I spent half a month making a beautiful application, but found that API Route cannot be used after building. I hope it can be supported.

**Comment by Mogeiman** [comment]
Was this solved? why was it closed?
