### ISSUE TITLE
consider option for naming background.js to something else

### ISSUE THREAD

**Issue by gautamsi** [saltyshiomix/nextron#50]
is it possible to use `app/background.js` (in package.json) to something else? I saw build directory [name to be `nextron`](https://github.com/saltyshiomix/nextron/issues/24), seems like that has been renamed to `app` any config option?

**Comment by gautamsi** [comment]
I was able to achieve like this

```js
const cwd = process.cwd();
const { resolve } = require("path");

module.exports = {
  webpack: (defaultConfig, env) => Object.assign(defaultConfig, {
    entry: {
      background: "./main/electron.ts",
    },
    output: {
      ...defaultConfig.output,
      filename: "electron.js",
      path: resolve(cwd, "electron"),
    }
  }),
};

not sure if that has any consequence to production build, will figure out :)
```

**Comment by saltyshiomix** [comment]
Hi @gautamsi 

Thank you for your questions!

It is not possible to rename `app/background.js` because we run `electron .` when development mode.

1. `$ electron .` (run electron with the current directory)
1. electron analyzes `./package.json#main`
  1. `package.json` main field must be one of these
    1. `index.js` (recommended by electron)
    1. `app/background.js` (the compatibility for `electron-builder`'s default source directory)

We adopt the `app/background.js` way because of simple directory structures.
(And because of the existence of apps based on source compiling like Next.js and typescript.)

If you use JavaScript only, the structure of just two files `index.js` and `index.html` is the simplest solution.

**Comment by saltyshiomix** [comment]
But if you have any another solutions, please send a PR at any time!

**Comment by saltyshiomix** [comment]
@gautamsi 

If you have any troubles, feel free to issue me up again :)
