### ISSUE TITLE
Redux integration possible ?

### ISSUE THREAD

**Issue by KASOGIT** [saltyshiomix/nextron#7]
Hi,
first i would like the say thanks for the idea, so thanks ! :)
My question is: will it works if i try to implements redux within nextron ? Because i guess internaly it's using export to html from nextjs right ?

Best regards.

**Comment by saltyshiomix** [comment]
Hi, @KASOGIT !
I'm really glad to hear that :)

Yes, it is possible to implement a redux way in nextron!
Also you are right: nextron uses `next export` internally, because **desktop binaries with production build** can deal with only static files.

In a `renderer` directory, you'll see a next.js way implementation.
Under the `renderer` directory, you can try any examples listed by official next.js repository 👍 

<https://github.com/zeit/next.js/tree/6.1.2/examples>

Redux ones:

<https://github.com/zeit/next.js/tree/6.1.2/examples/with-redux>
<https://github.com/zeit/next.js/tree/6.1.2/examples/with-redux-wrapper>
<https://github.com/zeit/next.js/tree/6.1.2/examples/with-redux-saga>
<https://github.com/zeit/next.js/tree/6.1.2/examples/with-redux-observable>
<https://github.com/zeit/next.js/tree/6.1.2/examples/with-redux-reselect-recompose>
<https://github.com/zeit/next.js/tree/6.1.2/examples/with-redux-code-splitting>

**Comment by KASOGIT** [comment]
Hi @saltyshiomix ! Gonna try this then :) I was affraid regarding implementing redux cause i was wondering if with static files dynamic pages could work.
